DATA:
  data_root: dataset/voc2012
  train_list: dataset/voc2012/list/train_aug.txt
  val_list: dataset/voc2012/list/val.txt
  classes: 21

TRAIN:
  backbone_name: facebook/dinov3-convnext-tiny-pretrain-lvd1689m
  use_fpn: True
  use_FiLM: True
  token_length: 768
  sync_bn: False  # adopt sync_bn or not
  train_h: 224
  train_w: 224
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8
  ignore_label: 255
  train_gpu: [0]
  workers: 64 # data loader workers
  batch_size: 32  # batch size for training
  batch_size_val: 32  # batch size for validation during training, memory and speed tradeoff
  lovasz_weight: 0.5
  lr: 0.01
  epochs: 50
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 10
  save_freq: 1
  save_path: exp/model
  weight:  # path to initial weight (default: none)
  resume:  
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: False
  world_size: 1
  rank: 0

TEST:
  test_list: dataset/voc2012/list/val.txt
  split: val  # split in [train, val and test]
  base_size: 512  # based size for scaling
  test_h: 224
  test_w: 224
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  model_path: exp/model/train_epoch_50.pth  # evaluation model path
  save_folder: exp/result/epoch_50/val/ss  # results save folder
  colors_path: data/voc2012/voc2012_colors.txt  # path of dataset colors
  names_path: data/voc2012/voc2012_names.txt  # path of dataset category names
